replicaCount: 1
image:
  repository: "nikhil1632"
  name: "order-service"
  tag: "latest"
component:
  value: "backend"
  pullPolicy: IfNotPresent
service:
  type: NodePort
  port: 3056
  targetPort: 9192
  nodePort: 30007
